/**
 * Filtre de contenu strict pour garantir un contenu professionnel
 * Bloque : émojis, ASCII décoratif, mentions d'IA
 */
class ContentFilter {
    constructor() {
        // Patterns regex pour détecter les éléments interdits
        this.emojiPattern = /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/u;
        
        this.asciiDecorativePatterns = [
            /[╔╗╚╝═║╠╣╬]/g,           // Boîtes
            /[▀▄█▌▐░▒▓]/g,            // Blocs
            /[◄►▲▼◊○●]/g,             // Formes géométriques
            /[★☆✦✧✨✩]/g,             // Étoiles décoratives
            /[─│┌┐└┘├┤┬┴┼]/g,        // Lignes de tableau ASCII
            /[━┃┏┓┗┛┣┫┳┻╋]/g,        // Lignes épaisses
            /[═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬]/g, // Doubles lignes
        ];

        this.aiMentionPatterns = [
            /\b(chatgpt|gpt-[0-9]|openai|claude|gemini|bard)\b/gi,
            /\b(intelligence artificielle|IA|AI|artificial intelligence)\b/gi,
            /\b(généré par|créé par|assisté par).*\b(IA|AI|intelligence artificielle)\b/gi,
            /\b(ce (texte|post|contenu) a été (généré|créé|écrit) (par|avec))\b/gi,
            /\b(powered by|generated by|created with).*(AI|chatgpt|gpt)\b/gi
        ];

        this.professionalStandards = {
            minLength: 50,
            maxLength: 3000, // Limite LinkedIn
            maxConsecutiveCapitals: 5,
            maxExclamationMarks: 2,
            allowedSpecialChars: ['-', '–', '—', ':', ',', '.', '!', '?', '"', "'", '(', ')', '%', '€', '$', '#']
        };
    }

    /**
     * Vérifie si le contenu respecte les standards professionnels
     * @param {string} content - Contenu à vérifier
     * @returns {Object} Résultat de validation avec détails
     */
    validate(content) {
        const violations = [];
        const warnings = [];

        // 1. Vérification des émojis
        if (this.emojiPattern.test(content)) {
            violations.push({
                type: 'EMOJI_DETECTED',
                severity: 'HIGH',
                message: 'Émojis détectés - Contenu non professionnel',
                matches: content.match(this.emojiPattern) || []
            });
        }

        // 2. Vérification ASCII décoratif
        const asciiViolations = this.detectAsciiArt(content);
        if (asciiViolations.length > 0) {
            violations.push({
                type: 'ASCII_DECORATIVE',
                severity: 'HIGH',
                message: 'Caractères ASCII décoratifs détectés',
                matches: asciiViolations
            });
        }

        // 3. Vérification mentions d'IA
        const aiMentions = this.detectAIMentions(content);
        if (aiMentions.length > 0) {
            violations.push({
                type: 'AI_MENTION',
                severity: 'CRITICAL',
                message: 'Mentions explicites d\'IA détectées',
                matches: aiMentions
            });
        }

        // 4. Vérifications professionnelles
        const lengthCheck = this.checkLength(content);
        if (!lengthCheck.valid) {
            violations.push({
                type: 'LENGTH_INVALID',
                severity: 'MEDIUM',
                message: lengthCheck.message,
                current: content.length,
                expected: `${this.professionalStandards.minLength}-${this.professionalStandards.maxLength}`
            });
        }

        // 5. Capitales excessives (SPAM-like)
        const capsCheck = this.checkExcessiveCapitals(content);
        if (capsCheck.excessive) {
            warnings.push({
                type: 'EXCESSIVE_CAPITALS',
                severity: 'LOW',
                message: 'Majuscules excessives détectées (style spam)',
                count: capsCheck.count
            });
        }

        // 6. Ponctuation excessive
        const punctuationCheck = this.checkExcessivePunctuation(content);
        if (punctuationCheck.excessive) {
            warnings.push({
                type: 'EXCESSIVE_PUNCTUATION',
                severity: 'LOW',
                message: 'Ponctuation excessive (!!! ???)',
                count: punctuationCheck.count
            });
        }

        return {
            valid: violations.length === 0,
            professional: violations.length === 0 && warnings.length === 0,
            violations,
            warnings,
            score: this.calculateProfessionalismScore(violations, warnings),
            recommendation: this.generateRecommendation(violations, warnings)
        };
    }

    /**
     * Détecte les caractères ASCII décoratifs
     * @private
     */
    detectAsciiArt(content) {
        const matches = [];
        
        this.asciiDecorativePatterns.forEach(pattern => {
            const found = content.match(pattern);
            if (found) {
                matches.push(...found);
            }
        });

        return [...new Set(matches)]; // Dédupliquer
    }

    /**
     * Détecte les mentions d'IA
     * @private
     */
    detectAIMentions(content) {
        const matches = [];
        
        this.aiMentionPatterns.forEach(pattern => {
            const found = content.match(pattern);
            if (found) {
                matches.push(...found);
            }
        });

        return [...new Set(matches)];
    }

    /**
     * Vérifie la longueur du contenu
     * @private
     */
    checkLength(content) {
        const length = content.length;
        
        if (length < this.professionalStandards.minLength) {
            return {
                valid: false,
                message: `Contenu trop court (${length} caractères). Minimum : ${this.professionalStandards.minLength}`
            };
        }
        
        if (length > this.professionalStandards.maxLength) {
            return {
                valid: false,
                message: `Contenu trop long (${length} caractères). Maximum : ${this.professionalStandards.maxLength}`
            };
        }

        return { valid: true };
    }

    /**
     * Vérifie les majuscules excessives
     * @private
     */
    checkExcessiveCapitals(content) {
        const consecutiveCapitalsPattern = new RegExp(`[A-Z]{${this.professionalStandards.maxConsecutiveCapitals + 1},}`, 'g');
        const matches = content.match(consecutiveCapitalsPattern);
        
        return {
            excessive: matches !== null && matches.length > 0,
            count: matches ? matches.length : 0,
            examples: matches ? matches.slice(0, 3) : []
        };
    }

    /**
     * Vérifie la ponctuation excessive
     * @private
     */
    checkExcessivePunctuation(content) {
        const exclamationCount = (content.match(/!/g) || []).length;
        const questionCount = (content.match(/\?/g) || []).length;
        const excessivePunctuation = /[!?]{3,}/g;
        
        return {
            excessive: exclamationCount > this.professionalStandards.maxExclamationMarks || 
                      excessivePunctuation.test(content),
            count: exclamationCount + questionCount
        };
    }

    /**
     * Calcule un score de professionnalisme
     * @private
     */
    calculateProfessionalismScore(violations, warnings) {
        let score = 100;

        violations.forEach(v => {
            switch (v.severity) {
                case 'CRITICAL':
                    score -= 40;
                    break;
                case 'HIGH':
                    score -= 25;
                    break;
                case 'MEDIUM':
                    score -= 15;
                    break;
                default:
                    score -= 10;
            }
        });

        warnings.forEach(() => {
            score -= 5;
        });

        return Math.max(0, score);
    }

    /**
     * Génère des recommandations d'amélioration
     * @private
     */
    generateRecommendation(violations, warnings) {
        if (violations.length === 0 && warnings.length === 0) {
            return 'Contenu conforme aux standards professionnels';
        }

        const recommendations = [];

        violations.forEach(v => {
            switch (v.type) {
                case 'EMOJI_DETECTED':
                    recommendations.push('Supprimez tous les émojis pour un ton professionnel');
                    break;
                case 'ASCII_DECORATIVE':
                    recommendations.push('Retirez les caractères ASCII décoratifs (boîtes, symboles)');
                    break;
                case 'AI_MENTION':
                    recommendations.push('CRITIQUE : Ne mentionnez jamais l\'utilisation d\'une IA');
                    break;
                case 'LENGTH_INVALID':
                    recommendations.push(v.message);
                    break;
            }
        });

        warnings.forEach(w => {
            switch (w.type) {
                case 'EXCESSIVE_CAPITALS':
                    recommendations.push('Réduisez les majuscules (style trop agressif)');
                    break;
                case 'EXCESSIVE_PUNCTUATION':
                    recommendations.push('Limitez les points d\'exclamation et d\'interrogation');
                    break;
            }
        });

        return recommendations.join(' | ');
    }

    /**
     * Nettoie automatiquement le contenu (si possible)
     * @param {string} content - Contenu à nettoyer
     * @returns {Object} Contenu nettoyé + rapport
     */
    autoClean(content) {
        let cleaned = content;
        const changes = [];

        // 1. Suppression des émojis
        if (this.emojiPattern.test(cleaned)) {
            cleaned = cleaned.replace(this.emojiPattern, '');
            changes.push('Émojis supprimés');
        }

        // 2. Suppression ASCII décoratif
        this.asciiDecorativePatterns.forEach(pattern => {
            if (pattern.test(cleaned)) {
                cleaned = cleaned.replace(pattern, '');
                changes.push('Caractères ASCII décoratifs supprimés');
            }
        });

        // 3. Suppression mentions d'IA (remplacées par formulations génériques)
        this.aiMentionPatterns.forEach(pattern => {
            if (pattern.test(cleaned)) {
                cleaned = cleaned.replace(pattern, '[contenu professionnel]');
                changes.push('Mentions d\'IA masquées');
            }
        });

        // 4. Nettoyage espaces multiples
        cleaned = cleaned.replace(/\s{3,}/g, ' ').trim();

        return {
            original: content,
            cleaned,
            changes,
            improved: changes.length > 0,
            validationResult: this.validate(cleaned)
        };
    }
}

module.exports = new ContentFilter();
